<a href="https://colab.research.google.com/github/flzhfi/deep-learning-assignments/blob/main/week05-DNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**[5주차]과제**
- 아래의 과제1)의 코드를 완성하시오.
- 모든 코드의 결과를 출력하여, .ipynb의 링크를 **[5주차]/[5주차]과제**에 제출하시오.\
(실습 제출 예시: 5주차_2020XXXX_이름.ipynb 코드 링크)

In [ ]:
print("2353764", "신예진")

2353764 신예진

In [ ]:
from google.colab import auth

auth.authenticate_user()
!gcloud config get-value account

snayou2@gmail.com

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#작업폴더 경로 참고 : data파일이 있는 폴더의 경로를 작성
workspace_path = '/content/drive/MyDrive/deeplearning/week05-test'

# [과제 1] activation func, hyper-parameter, optimizer등을 변경하여 와인 품질(quality)를 예측하는 모델의 accuracy(정확도)를 0.5 이상의 성능을 달성하여라.

## 조건 :
1. epoch 수는 최대 20으로 제한
2. 모델의 레이어는 2개(입력층, 출력층)로 제한
3. 입력층의 노드수는 256개로 하고 input_shape은 xTrain.shape[1]과 동일한 값으로 설정할 것

    예시) layer추가
```python
# 입력층 예시
netwrok.add(tf.keras.layers.Dense(노드 수, activation_func='activation_func', input_shape=xTrain.shape[1], kernel_initializer=initializer))
# 출력층 예시
network.add(tf.keras.layers.Dense(노드 수, activation='activation_func', kernel_initializer=initializer))

##- 개선사항을 작성해 주세요 :
1. 학습률을 0.001로 낮췄습니다.
2. epochs를 20으로 늘리고, batch_size를 32로 설정했습니다.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [ ]:
red_df = pd.read_csv(os.path.join(workspace_path,'winequality-red.csv'), sep=';', header=0, engine='python')
red_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
white_df = pd.read_csv(os.path.join(workspace_path,'winequality-white.csv'), sep=';', header=0, engine='python')
white_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [ ]:
wine =  pd.concat([red_df, white_df])

In [ ]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6497 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 659.9 KB

In [ ]:
sorted(wine.quality.unique())

[np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [ ]:
wine.quality.value_counts()

quality
6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: count, dtype: int64

In [ ]:
# 코드를 작성해 주세요
# 레이블링 인코딩 필요
# 힌트 : ?? = ??.apply(lambda x: x-3)

wine = pd.concat([red_df, white_df])  # red와 white 와인 데이터 합치기

wine['quality'] = wine['quality'].apply(lambda x: x - 3)
# lamda를 사용, -3을 하여 인덱스를 0부터 시작하게 함

sorted(wine.quality.unique()) # 변환 확인

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6)]

In [ ]:
sorted(wine.quality.unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6)]

In [ ]:
# 코드를 작성해 주세요
# 힌트 : 와인의 품질을 예측하는 모델이므로 훈련 데이터셋도 품질에 훈련셋으로 준비되어야 함
# xTrain = ??.drop(???, axis=1)
# yTrain = ??

# 데이터 분리
xTrain = wine.drop('quality', axis=1) # quality 제외한 나머지: 입력데이터
yTrain = wine['quality']  # 정답 값

In [ ]:
xTrain, xTest, yTrain, yTest = train_test_split(xTrain, yTrain, test_size=0.2)

In [ ]:
# 실험 결과 재현을 위한 seed 고정
SEED = 4
os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['TF_DETERMINISTIC_OPS'] = '1'
tf.random.set_seed(SEED)
initializer = tf.keras.initializers.HeNormal(seed=SEED)

In [ ]:
def build_model():
  network = tf.keras.models.Sequential()

  # 입력층, 노드 256개, ReLU 사용
  network.add(tf.keras.layers.Dense(256, activation='relu', input_shape=(xTrain.shape[1],), kernel_initializer='he_normal'))

  # 출력층
  network.add(tf.keras.layers.Dense(len(sorted(wine.quality.unique())), activation='softmax', kernel_initializer='he_normal'))

  # 학습률
  optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

  network.compile(optimizer=optimizer,
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

  return network

model = build_model()

history = model.fit(xTrain, yTrain, epochs=20, batch_size=32, validation_split=0.25)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.3231 - loss: 6.9729 - val_accuracy: 0.3221 - val_loss: 1.7531
Epoch 2/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.3532 - loss: 1.9118 - val_accuracy: 0.4394 - val_loss: 1.5789
Epoch 3/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.3924 - loss: 1.7240 - val_accuracy: 0.4558 - val_loss: 1.4141
Epoch 4/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4123 - loss: 1.5144 - val_accuracy: 0.4865 - val_loss: 1.3377
Epoch 5/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4241 - loss: 1.5105 - val_accuracy: 0.5000 - val_loss: 1.2991
Epoch 6/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4357 - loss: 1.4725 - val_accuracy: 0.5106 - val_loss: 1.3112
Epoch 7/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4408 - loss: 1.4450 - val_accuracy: 0.5212 - val_loss: 1.2725
Epoch 8/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4466 - loss: 1.4718 - val_accuracy: 0.5163 - val_loss: 1.3152
Epoch 9/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4517 - loss: 1.4395 - val_accuracy: 0.5173 - val_loss: 1.2600
Epoch 10/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4604 - loss: 1.4172 - val_accuracy: 0.5212 - val_loss: 1.2415
Epoch 11/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4629 - loss: 1.3937 - val_accuracy: 0.5183 - val_loss: 1.2432
Epoch 12/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4674 - loss: 1.3891 - val_accuracy: 0.5202 - val_loss: 1.2459
Epoch 13/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4662 - loss: 1.3902 - val_accuracy: 0.5163 - val_loss: 1.2490
Epoch 14/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4694 - loss: 1.3858 - val_accuracy: 0.5135 - val_loss: 1.2508
Epoch 15/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4678 - loss: 1.3825 - val_accuracy: 0.5125 - val_loss: 1.2559
Epoch 16/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4706 - loss: 1.3788 - val_accuracy: 0.5135 - val_loss: 1.2579
Epoch 17/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4732 - loss: 1.3724 - val_accuracy: 0.5125 - val_loss: 1.2623
Epoch 18/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4748 - loss: 1.3797 - val_accuracy: 0.5183 - val_loss: 1.2723
Epoch 19/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4783 - loss: 1.3595 - val_accuracy: 0.5163 - val_loss: 1.2799
Epoch 20/20
98/98 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4755 - loss: 1.3710 - val_accuracy: 0.5144 - val_loss: 1.2826

In [ ]:
test_loss, test_acc = model.evaluate(xTest, yTest)

33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5375 - loss: 1.2783

In [ ]:
print('테스트 정확도 : ', round(test_acc,3))

테스트 정확도 :  0.538